### ISSUE TITLE
No longer possible to be compiled by Mono's `mcs`

### ISSUE THREAD

**Issue by iahung2** [xiaoyuvax/bflata#10]
Mono doesn't support modern version of C#. Your code requires C# 11 (or C# 12?). Mono only supports C# 8. Please update your README.md to remove Mono from the list of supported compilers.

**Comment by iahung2** [comment]
Maybe the Mono in https://github.com/dotnet/runtime will be able to compile `bflata`.

**Comment by xiaoyuvax** [comment]
I am not sure. I think i'll drop mono, for it doesn't matter a lot.
